version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: dockerfiles/backend.Dockerfile

    volumes:
      - ./researchhub-backend:/researchhub-backend

    hostname: dev-backend.researchhub.com

    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

    expose:
      - 8000
    env_file:
      - .env.dev
    depends_on:
      - db
  web:
    image: node
    build:
      context: .
      dockerfile: dockerfiles/frontend.Dockerfile

    restart: unless-stopped

    volumes:
      - ./researchhub-web:/researchhub-web

    hostname: dev.researchhub.com
    expose:
      - 3000

  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    env_file:
      - .env.dev
  nginx: 

    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/

    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - backend

  redis:
    image: docker.io/bitnami/redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    expose:
      - 6379
    volumes:
      - 'redis_data:/bitnami/redis/data'

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - 9200:9200
      - 9300:9300

    restart: unless-stopped

    networks:
      - researchhub-network

    environment:
      - discovery.type=single-node
      - node.name=researchhub-elasticsearch
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
    driver: local

networks:
  researchhub-network:
    driver: bridge